### ISSUE TITLE
Abstract out the core functionality of this plugin for custom dictionaries?

### ISSUE THREAD

**Issue by jsit** [aaronspring/ncl_lazy_vim#1]
This looks like just what I've been looking for, but I don't use CDO or NCL; I'd love to have the core idea behind this plugin but with the ability to define and use custom dictionary files.

Would it be at all possible to create a version like that? I think It would be greatly welcomed by the community.

Thanks!

**Comment by aaronspring** [comment]
I got an abstract answer wie stackexchange while coding this: 
https://unix.stackexchange.com/questions/308290/vim-manipulate-dictionary-popup-for-autocompletion
The core functionality can be found in the vim documentation searching complete-functions

**Comment by jsit** [comment]
Thanks -- I hope you don't mind I've done this myself: https://github.com/jsit/vim-customcpt
