### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by yongpz** [aaronspring/ncl_lazy_vim#2]
Hello,

When run vim ./temp.ncl, I get that:

Error detected while processing /home/joker/.vimrc:
line   87:
E121: Undefined variable: s:vars_completion
E15: Invalid expression: empty(s:cdo_installed) && s:vars_completion == 'ENABLE'
Press ENTER or type command to continue

And I read the .vimrc. After I copy "let s:vars_completion = 'ENABLE'"  to the front, there is no errors.

![image](https://user-images.githubusercontent.com/29646575/41016409-b6680642-6981-11e8-8202-58aa2bef00af.png)

**Comment by aaronspring** [comment]
Hi,
thanks for the comment. There was an inconsistency between the example.vimrc and the add_ncl_complete_to_your_vimrc content. It should be defined at the beginning of the new vimrc part whether vars_completition should be used or not. If the requirements are not met, it is set DISABLE. But before it must be initialised to DISABLE or ENABLE.

Should be fixed now.
